# Generated by Django 6.0.6 on 2026-06-22 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilAgricola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cuenta', models.CharField(choices=[('comprador', 'Soy Comprador'), ('distribuidor', 'Soy Distribuidor')], max_length=20)),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre Completo o Empresa')),
                ('rif_cedula', models.CharField(max_length=50, unique=True, verbose_name='RIF / Cédula')),
                ('telefono', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=200)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
